version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - monitoring
    security_opt:
      - apparmor=unconfined

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - flask-app

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3030:3000"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
